[project]
name = "shadertoys"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "opencv-python-headless>=4.13.0.92",
    "polars>=1.38.1",
    "tqdm>=4.67.3",
]
